import type { Metadata } from 'next';
import {
  arcadeFill,
  arcadeOutline,
  pixelBody,
  pixelCaps,
  pixelHeader,
  pixelMono,
} from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`
        ${arcadeFill.variable} ${arcadeOutline.variable} ${pixelHeader.variable} ${pixelBody.variable} ${pixelCaps.variable} ${pixelMono.variable}
    `}
    >
      <body className='font-body'>{children}</body>
    </html>
  );
}
